# Generated by Django 5.1.7 on 2025-03-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donationname',
            field=models.CharField(choices=[('FOOD DONATION', 'FOOD DONATION'), ('CLOTHES DONATION', 'CLOTHES DONATION'), ('FOOTWEAR DONATION', 'FOOTWEAR DONATION'), ('BOOKS DONATION', 'BOOKS DONATION'), ('FOOD DONATION', 'FOOD DONATION'), ('FURNITURE DONATION', 'FURNITURE DONATION'), ('VESSEL DONATION', 'VESSEL DONATION'), ('OTHER DONATION', 'OTHER DONATION')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(default='pending', max_length=200),
        ),
    ]
