# Generated by Django 5.1.7 on 2025-03-25 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_donation_donationname_alter_donation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donationarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.donationarea'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.volunteer'),
        ),
    ]
